I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 240, in script
    $ psycha = cechy["EMP"] * 10
  File "game/script.rpy", line 240, in <module>
    $ psycha = cechy["EMP"] * 10
KeyError: 'EMP'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 240, in script
    $ psycha = cechy["EMP"] * 10
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 240, in <module>
    $ psycha = cechy["EMP"] * 10
KeyError: 'EMP'

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
CyberDzban 0.000000008
Sun Aug 11 10:22:57 2024
