I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1651, in script
    $ edki += 2 * randint(1,10)
  File "game/script.rpy", line 1651, in <module>
    $ edki += 2 * randint(1,10)
NameError: name 'randint' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1651, in script
    $ edki += 2 * randint(1,10)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 1651, in <module>
    $ edki += 2 * randint(1,10)
NameError: name 'randint' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
CyberDzban 0.0000000006
Wed Feb 21 17:31:16 2024
