I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/0bobcachievements.rpy", line 22, in script
    define BOBCACHIEVEMENT_LIST = (
  File "game/0bobcachievements.rpy", line 36, in <module>
    ("Ttsd", _("TO TAK SIĘ DA?"), _("Umarłeś przy tworzeniu postaci."), True)
TypeError: 'tuple' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/0bobcachievements.rpy", line 22, in script
    define BOBCACHIEVEMENT_LIST = (
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ast.py", line 2219, in execute
    self.set()
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ast.py", line 2233, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/0bobcachievements.rpy", line 36, in <module>
    ("Ttsd", _("TO TAK SIĘ DA?"), _("Umarłeś przy tworzeniu postaci."), True)
TypeError: 'tuple' object is not callable

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
CyberDzban 0.000000005
Wed Jul 31 11:59:03 2024
